auth:
  secret: "secret"
db:
  addr: "localhost:3306"
  name: "restapidb"
  user: "user"
  pass: "password"
redis:
  addr: "localhost:6379"
  pass: "password"
trace:
  addr: "localhost:6831"
  service_name: "restapi"