// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"
	productmodel "restapi/module/product/productmodel"

	mock "github.com/stretchr/testify/mock"
)

// ProductBusiness is an autogenerated mock type for the ProductBusiness type
type ProductBusiness struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *ProductBusiness) Create(ctx context.Context, req *productmodel.CreateReq) (*productmodel.CreateRes, error) {
	ret := _m.Called(ctx, req)

	var r0 *productmodel.CreateRes
	if rf, ok := ret.Get(0).(func(context.Context, *productmodel.CreateReq) *productmodel.CreateRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productmodel.CreateRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *productmodel.CreateReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProductBusiness interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductBusiness creates a new instance of ProductBusiness. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductBusiness(t mockConstructorTestingTNewProductBusiness) *ProductBusiness {
	mock := &ProductBusiness{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
