// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	tokenprovider "restapi/pkg/tokenprovider"
)

// TokenProvider is an autogenerated mock type for the TokenProvider type
type TokenProvider struct {
	mock.Mock
}

// Validate provides a mock function with given fields: token
func (_m *TokenProvider) Validate(token string) (*tokenprovider.TokenPayload, error) {
	ret := _m.Called(token)

	var r0 *tokenprovider.TokenPayload
	if rf, ok := ret.Get(0).(func(string) *tokenprovider.TokenPayload); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tokenprovider.TokenPayload)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTokenProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewTokenProvider creates a new instance of TokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTokenProvider(t mockConstructorTestingTNewTokenProvider) *TokenProvider {
	mock := &TokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
